#!/usr/bin/env python3
"""
PROJECT-TURBO | Enum Intelligence Extractor
Parses ggml.h and llama.h to extract TurboQuant enum values.
Auto-generates src/turbo/enums.py — no hardcoding, always in sync.

Usage:
    python scripts/extract_enums.py /path/to/ggml.h src/turbo/enums.py
    python scripts/extract_enums.py /path/to/ggml.h /path/to/llama.h src/turbo/enums.py
"""

import re
import sys
from pathlib import Path


# Enums we care about from ggml.h
GGML_TYPE_PATTERN = re.compile(r"GGML_TYPE_(\w+)\s*=\s*(\d+)")
GGML_OP_PATTERN = re.compile(r"GGML_OP_(\w+)\s*=\s*(\d+)")

# Incremental enum pattern (no explicit value, auto-increment)
GGML_TYPE_INCREMENTAL = re.compile(r"GGML_TYPE_(\w+)\s*(?:,|//|$)")
GGML_OP_INCREMENTAL = re.compile(r"GGML_OP_(\w+)\s*(?:,|//|$)")

# TurboQuant-specific markers — covers all known fork naming conventions
# spiritbuun/animehacker: TQ1_0, TQ2_0, TURBO3_0, TURBO4_0, TURBO2_0
# Madreag: TURBO3_0, TURBO4_0, TURBO2_0
# tq-kv (Rust): TQ3_0
TURBO_TYPES = {"TURBO3_0", "TURBO4_0", "TURBO2_0", "TQ1_0", "TQ2_0", "TQ3_0", "COUNT"}
TURBO_OPS = {"TURBO_WHT"}


def parse_explicit_enums(text: str, pattern: re.Pattern) -> dict[str, int]:
    """Parse enums with explicit integer values."""
    return {name: int(val) for name, val in pattern.findall(text)}


def parse_incremental_enums(
    text: str, pattern: re.Pattern, start: int = 0
) -> dict[str, int]:
    """Parse enums without explicit values (auto-increment from start)."""
    result = {}
    current = start
    for match in pattern.finditer(text):
        name = match.group(1)
        # Skip if this line has an explicit = value (handled by explicit parser)
        line = text[match.start() : match.start() + 200].split("\n")[0]
        if "=" in line:
            continue
        result[name] = current
        current += 1
    return result


def extract_from_header(filepath: str) -> tuple[dict[str, int], dict[str, int]]:
    """Extract ggml_type and ggml_op enums from a header file."""
    text = Path(filepath).read_text()

    # Extract enum ggml_type block
    type_block_match = re.search(r"enum\s+ggml_type\s*\{(.*?)\};", text, re.DOTALL)
    type_block = type_block_match.group(1) if type_block_match else ""

    # Extract enum ggml_op block
    op_block_match = re.search(r"enum\s+ggml_op\s*\{(.*?)\};", text, re.DOTALL)
    op_block = op_block_match.group(1) if op_block_match else ""

    # Parse explicit values first
    types = parse_explicit_enums(type_block, GGML_TYPE_PATTERN)
    ops = parse_explicit_enums(op_block, GGML_OP_PATTERN)

    # Merge incremental (only for entries not already captured)
    for name, val in parse_incremental_enums(type_block, GGML_TYPE_INCREMENTAL).items():
        if name not in types:
            types[name] = val

    for name, val in parse_incremental_enums(op_block, GGML_OP_INCREMENTAL).items():
        if name not in ops:
            ops[name] = val

    return types, ops


def generate_enums_py(
    types: dict[str, int], ops: dict[str, int], output_path: str
) -> None:
    """Generate src/turbo/enums.py from extracted enum values."""
    lines = [
        '"""',
        "PROJECT-TURBO | Auto-generated enum values",
        "DO NOT EDIT MANUALLY — generated by scripts/extract_enums.py",
        '"""',
        "",
        "# ── ggml_type enum values ───────────────────────────────────────────",
    ]

    # TurboQuant types first (most important)
    turbo_types = {k: v for k, v in types.items() if k in TURBO_TYPES}
    other_types = {k: v for k, v in types.items() if k not in TURBO_TYPES}

    for name in sorted(turbo_types.keys(), key=lambda x: turbo_types[x]):
        lines.append(f"GGML_TYPE_{name} = {turbo_types[name]}")

    lines.append("")
    lines.append("# ── All ggml_type values (reference) ────────────────────────")
    for name in sorted(other_types.keys(), key=lambda x: other_types[x]):
        lines.append(f"GGML_TYPE_{name} = {other_types[name]}")

    lines.append("")
    lines.append("# ── ggml_op enum values (TurboQuant ops) ────────────────────")
    for name in sorted(TURBO_OPS):
        if name in ops:
            lines.append(f"GGML_OP_{name} = {ops[name]}")

    lines.append("")
    lines.append("# ── Convenience maps ────────────────────────────────────────")
    lines.append("TURBO_TYPE_MAP = {")
    for cache_name, enum_name in [
        ("turbo3", "TURBO3_0"),
        ("turbo4", "TURBO4_0"),
        ("turbo2", "TURBO2_0"),
    ]:
        if enum_name in types:
            lines.append(f'    "{cache_name}": GGML_TYPE_{enum_name},')
    lines.append("}")
    lines.append("")
    lines.append(
        f"GGML_TYPE_COUNT = {types.get('COUNT', types.get('TURBO2_0', 44) + 1)}"
    )

    lines.append("")
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n")
    print(f"[ENUMS] Generated {output} ({len(types)} types, {len(ops)} ops)")


def main():
    if len(sys.argv) < 3:
        print("Usage: extract_enums.py <ggml.h> [llama.h] <output.py>")
        sys.exit(1)

    headers = sys.argv[1:-1]
    output = sys.argv[-1]

    all_types: dict[str, int] = {}
    all_ops: dict[str, int] = {}

    for header in headers:
        if not Path(header).exists():
            print(f"[ENUMS] WARNING: {header} not found, skipping")
            continue
        types, ops = extract_from_header(header)
        all_types.update(types)
        all_ops.update(ops)
        print(f"[ENUMS] Parsed {header}: {len(types)} types, {len(ops)} ops")

    if not all_types:
        print("[ENUMS] ERROR: No enums found. Check header paths.")
        sys.exit(1)

    # Print TurboQuant-specific findings
    print("[ENUMS] ── TurboQuant Types ──")
    for name in sorted(TURBO_TYPES):
        if name in all_types:
            print(f"[ENUMS]   GGML_TYPE_{name} = {all_types[name]}")

    print("[ENUMS] ── TurboQuant Ops ──")
    for name in sorted(TURBO_OPS):
        if name in all_ops:
            print(f"[ENUMS]   GGML_OP_{name} = {all_ops[name]}")

    generate_enums_py(all_types, all_ops, output)


if __name__ == "__main__":
    main()
